server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        default_schema: store_schema
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: postgres
    password: postgres
  liquibase:
    enabled: false

springdoc:
  swagger-ui:
    path: /store/swagger-ui